### ISSUE TITLE
Configurable Channels

### ISSUE THREAD

**Issue by TheGlitch76** [Kord-Extensions/ext-mappings#1]
# Summary
Channels right now are fairly hardcoded and include references that aren't needed in many discord servers (Namely, Patchwork, which I would like to be removed)

# Current Behavior
The Legacy and Patchwork channels are hardcoded to 1.2.5 and 1.14.4 respectively, and are always present
# Preferred Behavior
Server owners or bot maintainers should have an easy way to create their own channels through commands or configuration in the bot, and these default alternative channels (besides default and snapshot) should be removed

**Comment by TheGlitch76** [comment]
From my cursory glance at the code #2 absolutely requires replacing linkie core's YarnNamespace, so if #2 is going to be implemented that shouldn't be a concern

**Comment by gdude2002** [comment]
Yarn's extra channels may now be configured - although Patchwork is the only extra channel that `linkie-core` supports right now.

Commit: https://github.com/Kord-Extensions/ext-mappings/commit/4c45a299c795fbf7e2f21e389aea84ec749a6928

This hasn't yet been tested, so I'm not closing the issue yet.

**Comment by gdude2002** [comment]
After some testing, I'm going to say this issue is solved. Feel free to let me know if not!
