### ISSUE TITLE
Alternative Yarn versions should be disableable

### ISSUE THREAD

**Issue by TheGlitch76** [Kord-Extensions/ext-mappings#2]
# Summary
Fabric Discord is not going to want unofficial names in their bot, even if they are cc0

# Current Behavior
1.2.5, 1.8.9, etc. yarn alternatives are part of the ?yarn commands

# Preferred Behavior
Using the alternative yarn distributions should be disableable, or moved to their own namespace like MCP and Mojmap

**Comment by gdude2002** [comment]
Legacy Yarn has been moved to its own namespace in `linkie-core` already, so I've had to create a separate set of commands for it. This also means that the `legacy-yarn` namespace is configurable and may be disabled.

Commit: https://github.com/Kord-Extensions/ext-mappings/commit/4c45a299c795fbf7e2f21e389aea84ec749a6928

This hasn't been tested, so I'm not closing the issue yet.

**Comment by gdude2002** [comment]
After some testing, I'm going to say this issue is solved. Feel free to let me know if not!
