### ISSUE TITLE
Method mappings obfuscated names are incorrect.

### ISSUE THREAD

**Issue by sschr15** [Kord-Extensions/ext-mappings#3]
# Description

Requesting method mappings from any mapping set incorrectly shows the name of the parent class instead of its own name in the obfuscated parameter. I have tested this against every supported mapping set that the Tiny Potato bot on Fabricomm supports.

# Suggestions

If you have any ideas on solutions to this problem, feel free to leave them in this section.
Any research you've done can also go here.

# Media

<details>
    <summary>Current behavior (Click to expand)</summary>
    <img src="https://user-images.githubusercontent.com/15277819/106539442-9d932a80-64c3-11eb-8ed5-691a5fb3ed4a.png"/>
</details>

<details>
    <summary>Mapping of parent class (Click to expand)</summary>
    <img src="https://user-images.githubusercontent.com/15277819/106539690-11cdce00-64c4-11eb-9a35-cafb0213f692.png"/>
</details>

**Comment by gdude2002** [comment]
Thanks!
