### ISSUE TITLE
Mention FabricMC repo in README

### ISSUE THREAD

**Issue by Geek202** [Kord-Extensions/ext-mappings#4]
It might be a good idea for the README to mention that you may have to add the Fabric maven as well as the repo for the extension.
Maybe something like
```markdown
_Note: You may also have to add the FabricMC maven repo as well if dependencies fail to resolve (url: `https://maven.fabricmc.net`)_
```
underneath the maven repo URL and artifact coordinates?

**Comment by gdude2002** [comment]
Thanks for the heads up!
